Add option to control pen types
Dibasic/SS13PaperworkSimulator pull request #57
Opened 2019-03-19 21:19 UTC by soryy708

2019-03-19 21:23 UTC, Dibasic commented on index.html
> +                <option value="Segoe Script, sans-serif">Fancy</option>
The fancy pen can only be #1c1713 and no other pens have that color (except a rainbow crayon set to exactly that hex, I suppose.)

If we don't want to handle populating that select just yet (and populating selectmenus in jQuery UI involves some frustrating issues, not certain glancing at this whether or not it ends up in a selectmenu by being in this dialog) then perhaps when 'fancy' is selected, the other select should automatically default to selecting the 'fancy' color.

2019-03-20 14:52 UTC, soryy708 commented
@Dibasic Changes done, ready for review.

2019-03-20 15:12 UTC, Dibasic requested changes
The fancy style-color binding doesn't seem to work and seems more complicated than it needs to be. Something like this:

```
    $('#pen-style-select').change(function () {
        if (this.val() === 'Fancy') {
            $('#pen-color-select').val('Fancy');
            updateFonts();
        }
    });
```
replacing the existing `.click()` binding should work, shouldn't it?

2019-03-20 15:18 UTC, soryy708 commented
@Dibasic What exactly doesn't seem to work for you?

2019-03-20 15:21 UTC, Dibasic commented
> 
> 
> @Dibasic What exactly doesn't seem to work for you?

Selecting 'Fancy' as the pen style does not change the pen color to 'Fancy.'

2019-03-20 15:27 UTC, soryy708 commented
@Dibasic It does. Isn't fancy just a particular shade of black?

2019-03-20 15:28 UTC, soryy708 commented
![image](https://user-images.githubusercontent.com/2157782/54697050-96fca380-4b35-11e9-8445-c618def108af.png)

2019-03-20 16:54 UTC, Dibasic commented
If it does, it's not changing the selected option on the color select. That option should always match what the actual color is. I believe using `.val()` to change the selected value would make the displayed text also change.

2019-03-20 17:13 UTC, soryy708 commented
@Dibasic It does change on my machine. Which browser are you using?

2019-03-20 17:32 UTC, Dibasic commented
Weird. I'm testing on Firefox 65.0.2.

2019-03-20 17:42 UTC, soryy708 commented
Odd. So am I!
Clear your cache?

Any errors in the dev console?

2019-03-20 17:49 UTC, Dibasic commented
Tested again and working. Weird.

Looks good, just some merge conflicts to resolve and it's good to go.

2019-03-20 17:49 UTC, Dibasic approved these changes

2019-03-20 17:54 UTC, Dibasic commented
Works. Looks nasty when used with pen colors, but that's for an issue.

2019-03-20 17:55 UTC, merged